# Name of the workflow
name: Unit and Integration tests
# This work flow is triggered when pull requests are opened or updated
on: [pull_request]
# A workflow run is made up of one or more jobs.
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Write firebase_options.dart
        run: echo '${{ secrets.FIREBASE_OPTIONS }}' > lib/firebase_options.dart

      - name: Run Unit Tests
        run: flutter test

  android-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Write firebase_options.dart
        run: echo '${{ secrets.FIREBASE_OPTIONS }}' > lib/firebase_options.dart
      - name: Write GoogleService-info.plist
        run: echo '${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}' > ios/Runner/GoogleService-Info.plist
      - name: Write google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > android/app/google-services.json
      - name: Write firebase.json
        run: echo '${{ secrets.FIREBASE_JSON }}' > firebase.json

      - name: Install firebase tools
        run: npm install -g firebase-tools

      - name: Authenticate firebase
        run: firebase use --token '${{ secrets.FIREBASE_TOKEN }}'

      - name: Run Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: firebase emulators:exec --token "${{ secrets.FIREBASE_TOKEN }}" "flutter test integration_test --timeout none" --import=./data

  iphone-integration-tests:
    runs-on: macOS-latest
    timeout-minutes: 50
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Write firebase_options.dart
        run: echo '${{ secrets.FIREBASE_OPTIONS }}' > lib/firebase_options.dart
      - name: Write GoogleService-info.plist
        run: echo '${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}' > ios/Runner/GoogleService-Info.plist
      - name: Write google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > android/app/google-services.json
      - name: Write firebase.json
        run: echo '${{ secrets.FIREBASE_JSON }}' > firebase.json

      - name: Install firebase tools
        run: npm install -g firebase-tools

      - name: Authenticate firebase
        run: firebase use --token '${{ secrets.FIREBASE_TOKEN }}'

      - name: "Set up simulator"
        uses: futureware-tech/simulator-action@v4
        with:
          model: "iPhone 14"
          os_version: ">=13.0"
          wait_for_boot: true
      - name: Get Flutter Dependencies
        run: flutter pub get
      - name: Pod Install
        run: |
          cd ios
          pod install
          cd ..
      - name: "Run Integration Tests"
        run: firebase emulators:exec --token "${{ secrets.FIREBASE_TOKEN }}" "flutter test integration_test --timeout none" --import=./data
