# Name of the workflow
name: Unit and Integration tests
# This work flow is triggered when pull requests are opened or updated
on: [pull_request]
# A workflow run is made up of one or more jobs.
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Write firebase_options.dart
        run: echo '${{ secrets.FIREBASE_OPTIONS }}' > lib/firebase_options.dart

      - name: Run Unit Tests
        run: flutter test

  android-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Set Up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'



      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: Enabling KVM -1
        uses: DeterminateSystems/nix-installer-action@main

      - name: Enabling KVM -2
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Write firebase_options.dart
        run: echo '${{ secrets.FIREBASE_OPTIONS }}' > lib/firebase_options.dart
      - name: Write GoogleService-info.plist
        run: echo '${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}' > ios/Runner/GoogleService-Info.plist
      - name: Write google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > android/app/google-services.json
      - name: Write firebase.json
        run: echo '${{ secrets.FIREBASE_JSON }}' > firebase.json

      - name: Install firebase tools
        run: npm install -g firebase-tools

      - name: Authenticate firebase
        run: firebase use --token '${{ secrets.FIREBASE_TOKEN }}'

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Run Integration Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          script: firebase emulators:exec "flutter test integration_test --timeout none" --import=./android_emulator_data

  iphone-integration-tests:
    runs-on: macOS-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Erase all simulators
        run: xcrun simctl erase all

      - name: Cache Derived Data
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-xcode-deriveddata-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-xcode-deriveddata-

      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Write firebase_options.dart
        run: echo '${{ secrets.FIREBASE_OPTIONS }}' > lib/firebase_options.dart
      - name: Write GoogleService-info.plist
        run: echo '${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}' > ios/Runner/GoogleService-Info.plist
      - name: Write google-services.json
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > android/app/google-services.json
      - name: Write firebase.json
        run: echo '${{ secrets.FIREBASE_JSON }}' > firebase.json

      - name: Install firebase tools
        run: npm install -g firebase-tools

      - name: Authenticate firebase
        run: firebase use --token '${{ secrets.FIREBASE_TOKEN }}'
      - name: Get Flutter Dependencies
        run: |
          flutter pub get
      - name: Pod Install
        run: |
          cd ios
          pod install
          cd ..

      - name: "Set up simulator"
        uses: futureware-tech/simulator-action@v3
        with:
          os: iOS
          model: "iPhone SE (3rd generation)"
          os_version: ">=13.0"

      - name: Grant permission
        run: |
          brew tap wix/brew
          brew install applesimutils
          applesimutils --booted --bundle com.example.folio --setPermissions photos=YES,camera=YES

      - name: "Run Integration Tests"
        timeout-minutes: 120
        run: firebase emulators:exec --token "${{ secrets.FIREBASE_TOKEN }}" "flutter test integration_test --timeout none --verbose" --import=./data
